// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEth(arg1) {
  return window['go']['main']['NodeManager']['GetEth'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['main']['NodeManager']['OnStartup'](arg1);
}

export function SetEth(arg1) {
  return window['go']['main']['NodeManager']['SetEth'](arg1);
}
