// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetEth(arg1:string):Promise<main.Node>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SetEth(arg1:main.Node):Promise<Error>;
